[tool.autoflake]
in-place = true
recursive = true
exclude = [ 
    "v1" 
]
imports = [ 
    "django", 
    "requests", 
    "rest_framework" 
]
remove-all-unused-imports = true
ignore-init-module-imports = true
remove-duplicate-keys = true
remove-unused-variables = true
verbose = "2"

[tool.isort]
py_version = 3
skip_glob = [ 
    "v1/*",
    ".venv/*",
    "__pycache__/*"
]
only_modified = true
line_length = 80
verbose = true
virtual_env = ".venv/"
ensure_newline_before_comments = true
honor_noqa = true
force_alphabetical_sort = true
group_by_package = true
float_to_top = true
color_output = true
dedup_headings = true
overwrite_in_place = true
star_first = true
