# Generated by Django 4.2.5 on 2023-10-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuits',
            fields=[
                ('circuitId', models.IntegerField(primary_key=True, serialize=False)),
                ('circuitRef', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('alt', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Constructors',
            fields=[
                ('contructorId', models.IntegerField(primary_key=True, serialize=False)),
                ('constructorRef', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('disciplineId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driverId', models.IntegerField(primary_key=True, serialize=False)),
                ('driverRef', models.BigIntegerField()),
                ('number', models.IntegerField()),
                ('code', models.CharField(max_length=3)),
                ('firstname', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('raceId', models.IntegerField(primary_key=True, serialize=False)),
                ('round', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('url', models.CharField(max_length=255)),
                ('fp1_date', models.DateField()),
                ('fp1_time', models.TimeField()),
                ('fp2_date', models.DateField()),
                ('fp2_time', models.TimeField()),
                ('fp3_date', models.DateField()),
                ('fp3_time', models.TimeField()),
                ('quali_date', models.DateField()),
                ('quali_time', models.TimeField()),
                ('sprint_date', models.DateField()),
                ('sprint_time', models.TimeField()),
                ('circuitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.circuits')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusId', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SprintResults',
            fields=[
                ('sprintResultId', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('grid', models.IntegerField()),
                ('position', models.IntegerField()),
                ('positionText', models.CharField(max_length=255)),
                ('positionOrder', models.IntegerField()),
                ('points', models.FloatField()),
                ('laps', models.IntegerField()),
                ('time', models.CharField(max_length=255)),
                ('milliseconds', models.IntegerField()),
                ('fastestLap', models.IntegerField()),
                ('fastestLapTime', models.CharField(max_length=255)),
                ('statusId', models.IntegerField()),
                ('constructorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.constructors')),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.drivers')),
                ('raceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('disciplineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.disciplines')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('resultId', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('grid', models.IntegerField()),
                ('position', models.IntegerField()),
                ('positionText', models.CharField(max_length=255)),
                ('positionOrder', models.IntegerField()),
                ('points', models.FloatField()),
                ('laps', models.IntegerField()),
                ('time', models.CharField(max_length=255)),
                ('milliseconds', models.IntegerField()),
                ('fastestLap', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('fastestLapTime', models.CharField(max_length=255)),
                ('fastestLapSpeed', models.CharField(max_length=255)),
                ('statusId', models.IntegerField()),
                ('constructorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.constructors')),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.drivers')),
                ('raceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
        migrations.AddField(
            model_name='races',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.seasons'),
        ),
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('qualifyid', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('position', models.IntegerField()),
                ('q1', models.IntegerField()),
                ('q2', models.IntegerField()),
                ('q3', models.IntegerField()),
                ('constructorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.constructors')),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.drivers')),
                ('raceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
        migrations.CreateModel(
            name='PitStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.IntegerField()),
                ('lap', models.IntegerField()),
                ('time', models.TimeField()),
                ('duration', models.FloatField()),
                ('milliseconds', models.IntegerField()),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.drivers')),
                ('raceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
        migrations.CreateModel(
            name='LapTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap', models.IntegerField()),
                ('position', models.IntegerField()),
                ('time', models.FloatField()),
                ('milliseconds', models.IntegerField()),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.drivers')),
                ('raceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
        migrations.CreateModel(
            name='DriverStandings',
            fields=[
                ('driverStandingsId', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('position', models.IntegerField()),
                ('positionText', models.CharField(max_length=255)),
                ('wins', models.IntegerField()),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.drivers')),
                ('raceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructorStandings',
            fields=[
                ('constructorStandingsId', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('position', models.IntegerField()),
                ('positionText', models.CharField(max_length=255)),
                ('wins', models.IntegerField()),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.drivers')),
                ('raceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructorResults',
            fields=[
                ('constructorResultsId', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('constructorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.constructors')),
                ('raceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
    ]
