# Generated by Django 4.2.5 on 2023-10-24 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuits',
            fields=[
                ('circuitId', models.IntegerField(primary_key=True, serialize=False)),
                ('circuitRef', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('alt', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constructors',
            fields=[
                ('constructorId', models.IntegerField(primary_key=True, serialize=False)),
                ('constructorRef', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('disciplineId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driverId', models.IntegerField(primary_key=True, serialize=False)),
                ('driverRef', models.BigIntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('firstname', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('raceId', models.IntegerField(primary_key=True, serialize=False)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('fp1_date', models.DateField(blank=True, null=True)),
                ('fp1_time', models.TimeField(blank=True, null=True)),
                ('fp2_date', models.DateField(blank=True, null=True)),
                ('fp2_time', models.TimeField(blank=True, null=True)),
                ('fp3_date', models.DateField(blank=True, null=True)),
                ('fp3_time', models.TimeField(blank=True, null=True)),
                ('quali_date', models.DateField(blank=True, null=True)),
                ('quali_time', models.TimeField(blank=True, null=True)),
                ('sprint_date', models.DateField(blank=True, null=True)),
                ('sprint_time', models.TimeField(blank=True, null=True)),
                ('circuitId', models.ForeignKey(db_column='circuitId', on_delete=django.db.models.deletion.CASCADE, to='data.circuits')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusId', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SprintResults',
            fields=[
                ('sprintResultId', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('grid', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positionText', models.CharField(blank=True, max_length=255, null=True)),
                ('positionOrder', models.IntegerField(blank=True, null=True)),
                ('points', models.FloatField(blank=True, null=True)),
                ('laps', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('fastestLap', models.IntegerField(blank=True, null=True)),
                ('fastestLapTime', models.CharField(blank=True, max_length=255, null=True)),
                ('constructorId', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.CASCADE, to='data.constructors')),
                ('driverId', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.CASCADE, to='data.drivers')),
                ('raceId', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.CASCADE, to='data.races')),
                ('statusId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.status')),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('seasonId', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('disciplineId', models.ForeignKey(db_column='disciplineId', on_delete=django.db.models.deletion.CASCADE, to='data.disciplines')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('resultId', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('grid', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('positionText', models.CharField(blank=True, max_length=255, null=True)),
                ('positionOrder', models.IntegerField(blank=True, null=True)),
                ('points', models.FloatField(blank=True, null=True)),
                ('laps', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('fastestLap', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('fastestLapTime', models.CharField(blank=True, max_length=255, null=True)),
                ('fastestLapSpeed', models.CharField(blank=True, max_length=255, null=True)),
                ('constructorId', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.CASCADE, to='data.constructors')),
                ('driverId', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.CASCADE, to='data.drivers')),
                ('raceId', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.CASCADE, to='data.races')),
                ('statusId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.status')),
            ],
        ),
        migrations.AddField(
            model_name='races',
            name='seasonId',
            field=models.ForeignKey(db_column='seasonId', on_delete=django.db.models.deletion.CASCADE, to='data.seasons'),
        ),
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('qualifyid', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('q1', models.IntegerField(blank=True, null=True)),
                ('q2', models.IntegerField(blank=True, null=True)),
                ('q3', models.IntegerField(blank=True, null=True)),
                ('constructorId', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.CASCADE, to='data.constructors')),
                ('driverId', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.CASCADE, to='data.drivers')),
                ('raceId', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
        migrations.CreateModel(
            name='PitStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.IntegerField()),
                ('lap', models.IntegerField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('driverId', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.CASCADE, to='data.drivers')),
                ('raceId', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
        migrations.CreateModel(
            name='LapTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('time', models.FloatField(blank=True, null=True)),
                ('milliseconds', models.IntegerField(blank=True, null=True)),
                ('driverId', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.CASCADE, to='data.drivers')),
                ('raceId', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
        migrations.CreateModel(
            name='DriverStandings',
            fields=[
                ('driverStandingsId', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('position', models.IntegerField()),
                ('positionText', models.CharField(blank=True, max_length=255, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('driverId', models.ForeignKey(db_column='driverId', on_delete=django.db.models.deletion.CASCADE, to='data.drivers')),
                ('raceId', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructorStandings',
            fields=[
                ('constructorStandingsId', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('position', models.IntegerField()),
                ('positionText', models.CharField(blank=True, max_length=255, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('constructorId', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.CASCADE, to='data.constructors')),
                ('raceId', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructorResults',
            fields=[
                ('constructorResultsId', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('constructorId', models.ForeignKey(db_column='constructorId', on_delete=django.db.models.deletion.CASCADE, to='data.constructors')),
                ('raceId', models.ForeignKey(db_column='raceId', on_delete=django.db.models.deletion.CASCADE, to='data.races')),
            ],
        ),
    ]
