# Generated by Django 4.2.5 on 2023-10-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuits',
            name='alt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='circuitRef',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='constructorresults',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='constructorRef',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='constructorstandings',
            name='positionText',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='constructorstandings',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='driverRef',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driverstandings',
            name='positionText',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='driverstandings',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laptimes',
            name='milliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitstops',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitstops',
            name='milliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitstops',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='q1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='q2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualifying',
            name='q3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='fp1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='fp1_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='fp2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='fp2_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='fp3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='fp3_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='quali_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='quali_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='sprint_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='sprint_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='fastestLap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='fastestLapSpeed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='fastestLapTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='grid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='milliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='positionOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='positionText',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='statusId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sprintresults',
            name='fastestLap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprintresults',
            name='fastestLapTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sprintresults',
            name='grid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprintresults',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprintresults',
            name='milliseconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprintresults',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprintresults',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprintresults',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprintresults',
            name='positionOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprintresults',
            name='positionText',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sprintresults',
            name='statusId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprintresults',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
