# Generated by Django 4.2.5 on 2023-10-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_circuits_alt_alter_circuits_circuitref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
