# Generated by Django 4.2.5 on 2023-10-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructors',
            old_name='contructorId',
            new_name='constructorId',
        ),
    ]
